# GENERATED by `ggen sync run` (rule render-makefile-verify in ggen.toml).
# Consequence — edit schema/verify.ttl / schema/verify-gates.rq, never this
# file. One-command gate battery (ticket docs/sjira/v26.9.21/C8.md):
#   make verify = verify-gates (rendered runner, records evidence)
#               + ggen sync run (render + receipt)
#               + ggen receipt verify (receipt chain check)
# Standing vocabulary (ALIVE/BLOCKED/BUILD_BROKEN/…) is rendered from the
# packs/evidence-standing-pack es:Standing facts; per-gate red standings
# from schema/verify.ttl fdv:redStanding. Target-name law: claims `verify`
# and `verify-*` only (`sync`/`gates` belong to C10).

# standing vocabulary (es:standingName): alive
# standing vocabulary (es:standingName): blocked
# standing vocabulary (es:standingName): build_broken
# standing vocabulary (es:standingName): partial_alive
# standing vocabulary (es:standingName): unknown
# standing vocabulary (es:standingName): unsupported
SHELL := /bin/bash

.PHONY: verify verify-gates verify-build-workspace verify-clippy-deny-warnings verify-fmt-check verify-test-validation verify-test-workspace

verify: verify-gates
	ggen sync run
	ggen receipt verify

verify-gates:
	bash scripts/verify-gates.sh

verify-build-workspace:
	bash -c 'cargo build --workspace'

verify-clippy-deny-warnings:
	bash -c 'cargo clippy --workspace --all-targets --all-features -- -D warnings'

verify-fmt-check:
	bash -c 'cargo fmt --all -- --check'

verify-test-validation:
	bash -c 'cargo run -p test-validation'

verify-test-workspace:
	bash -c 'cargo test --workspace'

# --- C10 reconciliation targets (rule-owned since the wave-4 dry run: these
# bytes live in THIS owning template, not in a hand-unioned Makefile — the
# HANDWRITTEN.md multi-rule-union row is paid down. Failure modes this cures:
# every `ggen sync run` overwrote the hand-unioned block away (this rule owns
# Makefile in Overwrite mode), and the wave-4 integration merge had truncated
# the block's head: no GENESIS := / .PHONY / sync: / genesis-check: lines
# survived the union) ---
GENESIS := docs/GENESIS.md

.PHONY: sync genesis-check gates

sync:
	ggen sync run

# Proposed CI check-mode step (documented in GENESIS.md, NOT enabled):
#   ggen sync run --dry-run --format quiet && make genesis-check
genesis-check:
	@set -euo pipefail; \
	fail=0; checked=0; deferred=0; gaps=0; \
	while IFS=$$'\t' read -r cons src status; do \
	  [ -n "$$cons" ] || continue; \
	  label="[$$status] $$cons <- $$src"; \
	  case "$$status" in \
	    pending) \
	      if [ -e "$$src" ]; then \
	        echo "FAIL $$label (source landed — flip row to active in $(GENESIS))"; fail=$$((fail+1)); \
	      else \
	        echo "DEFERRED $$label (source not in this tree yet)"; deferred=$$((deferred+1)); \
	      fi ;; \
	    gap) \
	      if [ -e "$$cons" ]; then \
	        echo "GAP-OK $$label"; gaps=$$((gaps+1)); \
	      else \
	        echo "FAIL $$label (gap file missing)"; fail=$$((fail+1)); \
	      fi ;; \
	    active) \
	      ok=1; \
	      case "$$src" in \
	        upstream:*) \
	          ref="$${src##*@}"; \
	          if [[ "$$ref" =~ ^[0-9a-f]{40}$$ ]]; then \
	            git ls-files -s vendors/duckdb-rs | grep -q "$$ref" || { echo "FAIL $$label (vendors/duckdb-rs gitlink != $$ref)"; ok=0; }; \
	          else \
	            grep -q "$${ref#v}" schema/domain.ttl || { echo "FAIL $$label (pin $$ref absent from schema/domain.ttl)"; ok=0; }; \
	          fi ;; \
	        HANDWRITTEN.md) \
	          grep -qF "$$cons" HANDWRITTEN.md || { echo "FAIL $$label (no ledger row names this path)"; ok=0; }; \
	          [ -e "$$cons" ] || { echo "FAIL $$label (file missing)"; ok=0; } ;; \
	        hand:*|unknown:*) : ;; \
	        *) \
	          if [[ "$$src" == *[\[\*\?]* ]]; then \
	            compgen -G "$$src" >/dev/null || { echo "FAIL $$label (source glob unmatched)"; ok=0; }; \
	          else \
	            [ -e "$$src" ] || { echo "FAIL $$label (source missing)"; ok=0; }; \
	          fi ;; \
	      esac; \
	      case "$$cons" in \
	        ext:*) : ;; \
	        *[\[\*\?]*) \
	          compgen -G "$$cons" >/dev/null || { echo "FAIL $$label (consequence glob unmatched)"; ok=0; } ;; \
	        *) \
	          [ -e "$$cons" ] || { echo "FAIL $$label (consequence missing)"; ok=0; } ;; \
	      esac; \
	      if [ $$ok -eq 1 ]; then echo "OK $$label"; checked=$$((checked+1)); else fail=$$((fail+1)); fi ;; \
	    *) \
	      echo "FAIL $$label (unknown status '$$status')"; fail=$$((fail+1)) ;; \
	  esac; \
	done < <(awk -F'|' '/^\| `/ { c=$$2; s=$$3; t=$$4; gsub(/[` ]/,"",c); gsub(/[` ]/,"",s); gsub(/[` ]/,"",t); print c "\t" s "\t" t }' $(GENESIS)); \
	echo "genesis-check: checked=$$checked deferred=$$deferred gaps=$$gaps failed=$$fail"; \
	[ $$fail -eq 0 ]

gates: sync genesis-check
	@echo "GATES GREEN: sync exit 0 + genesis-check exit 0 (verify remains reserved for ticket C8)"
