# GENERATED by `ggen sync run` (rule render-makefile-verify in ggen.toml).
# Consequence — edit schema/verify.ttl / schema/verify-gates.rq, never this
# file. One-command gate battery (ticket docs/sjira/v26.9.21/C8.md):
#   make verify = verify-gates (rendered runner, records evidence)
#               + ggen sync run (render + receipt)
#               + ggen receipt verify (receipt chain check)
# Standing vocabulary (ALIVE/BLOCKED/BUILD_BROKEN/…) is rendered from the
# packs/evidence-standing-pack es:Standing facts; per-gate red standings
# from schema/verify.ttl fdv:redStanding. Target-name law: claims `verify`
# and `verify-*` only (`sync`/`gates` belong to C10).

# standing vocabulary (es:standingName): alive
# standing vocabulary (es:standingName): blocked
# standing vocabulary (es:standingName): build_broken
# standing vocabulary (es:standingName): partial_alive
# standing vocabulary (es:standingName): unknown
# standing vocabulary (es:standingName): unsupported
SHELL := /bin/bash

.PHONY: verify verify-gates verify-build-workspace verify-clippy-deny-warnings verify-fmt-check verify-test-validation verify-test-workspace

verify: verify-gates
	ggen sync run
	ggen receipt verify

verify-gates:
	bash scripts/verify-gates.sh

verify-build-workspace:
	bash -c 'cargo build --workspace'

verify-clippy-deny-warnings:
	bash -c 'cargo clippy --workspace --all-targets --all-features -- -D warnings'

verify-fmt-check:
	bash -c 'cargo fmt --all -- --check'

verify-test-validation:
	bash -c 'cargo run -p test-validation'

verify-test-workspace:
	bash -c 'cargo test --workspace'
