#!/usr/bin/env bash
# GENERATED by `ggen sync run` (rule render-verify-gates in ggen.toml).
# Consequence — edit schema/verify.ttl (the ver:RequiredCheck facts), never
# this file. Vocabularies: ver: packs/ggen-verify-pack,
# es: packs/evidence-standing-pack (bound via [ontology].imports).
# Runs every required check, records REAL exit codes as ver:Check facts in
# scripts/verify-evidence.ttl, and exits nonzero if any gate is red.
set -uo pipefail
cd "$(dirname "$0")/.."

EV="scripts/verify-evidence.ttl"
RECORDED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
GRAPH_HASH="unsynced"
if [ -f .ggen-v2/receipt.json ]; then
  GRAPH_HASH="$(python3 -c 'import json;print(json.load(open(".ggen-v2/receipt.json"))["payload"]["graph_hash"])' 2>/dev/null || echo unsynced)"
fi

NAMES=(); CODES=(); TOOLS=(); REDS=()
FAILED_RED=""

run_gate() { # name command redStandingName(lowercase, from es:standingName)
  name="$1"; cmd="$2"; red="$3"
  echo "=== [C8 gate] $name"
  log="$(mktemp -t verify-gate)"
  bash -c "$cmd" >"$log" 2>&1
  code=$?
  tail -n 3 "$log" | sed 's/^/    | /'
  rm -f "$log"
  NAMES+=("$name"); CODES+=("$code"); TOOLS+=("$cmd"); REDS+=("$red")
  if [ "$code" -ne 0 ] && [ -z "$FAILED_RED" ]; then FAILED_RED="$red"; fi
  return 0
}

run_gate 'build-workspace' 'cargo build --workspace' 'build_broken'
run_gate 'clippy-deny-warnings' 'cargo clippy --workspace --all-targets --all-features -- -D warnings' 'blocked'
run_gate 'fmt-check' 'cargo fmt --all -- --check' 'blocked'
run_gate 'test-validation' 'cargo run -p test-validation' 'build_broken'
run_gate 'test-workspace' 'cargo test --workspace' 'build_broken'


{
  echo "# GENERATED by scripts/verify-gates.sh at $RECORDED_AT -- do not edit."
  echo "# Real exit codes from real runs of the schema/verify.ttl gate battery."
  echo "# Vocabulary: ver: packs/ggen-verify-pack; standing: es: evidence-standing-pack."
  echo "@prefix ver: <http://seanchatmangpt.github.io/packs/ggen-verify#> ."
  echo ""
  SUBJECT_HEAD="$(git rev-parse HEAD 2>/dev/null || echo unknown)"
  SUBJECT_TREE="$(git rev-parse 'HEAD^{tree}' 2>/dev/null || echo unknown)"
  echo "ver:verifySubject ver:subjectHead \"$SUBJECT_HEAD\" ;"
  echo "    ver:subjectTree \"$SUBJECT_TREE\" ;"
  echo "    ver:recordedAt \"$RECORDED_AT\" ."
  echo ""
  i=0
  while [ "$i" -lt "${#NAMES[@]}" ]; do
    echo "ver:check-${NAMES[$i]} a ver:Check ;"
    echo "    ver:name \"${NAMES[$i]}\" ;"
    echo "    ver:tool \"${TOOLS[$i]}\" ;"
    echo "    ver:exitCode ${CODES[$i]} ;"
    echo "    ver:verifiedGraphHash \"$GRAPH_HASH\" ;"
    echo "    ver:recordedAt \"$RECORDED_AT\" ."
    echo ""
    i=$((i + 1))
  done
} > "$EV"

TOTAL=${#NAMES[@]}
GREEN=0
i=0
while [ "$i" -lt "$TOTAL" ]; do
  [ "${CODES[$i]}" -eq 0 ] && GREEN=$((GREEN + 1))
  i=$((i + 1))
done
echo "verify-gates: $GREEN/$TOTAL gates green -> $EV (graph hash binding: $GRAPH_HASH)"
i=0
while [ "$i" -lt "$TOTAL" ]; do
  echo "  ${NAMES[$i]}: exit ${CODES[$i]}"
  i=$((i + 1))
done


if [ -n "$FAILED_RED" ]; then
  echo "STANDING: $(echo "$FAILED_RED" | tr '[:lower:]' '[:upper:]') (red gate above; evidence: $EV)"
  exit 1
fi
echo "STANDING: ALIVE — all $TOTAL gates green (evidence: $EV)"
